export {
  getClientPlayerId,
  getRoomId,
  getSocketClient,
  getWorldId,
  listenToPlayerUpdates,
  listenToRoomChatMessages,
  onWebRTCAnswer,
  onWebRTCIceCandidate,
  onWebRTCOffer,
  sendInput,
  sendRoomChatMessage,
  sendWebRTCAnswer,
  sendWebRTCIceCandidate,
  sendWebRTCOffer,
  setPlayerAvatarId,
  setPlayerAvatarUrl,
  setPlayerName,
  setRoomId,
  setWorldId,
} from '@/network/socket/socketClient';
