export {
  getClientPlayerId,
  getRoomId,
  getSocketClient,
  listenToPlayerUpdates,
  onWebRTCAnswer,
  onWebRTCIceCandidate,
  onWebRTCOffer,
  sendInput,
  sendWebRTCAnswer,
  sendWebRTCIceCandidate,
  sendWebRTCOffer,
  setPlayerAvatarUrl,
  setPlayerName,
  setRoomId,
} from '@/network/socket/socketClient';
